### ISSUE TITLE
this[MODULE_TYPE] is not a function

### ISSUE THREAD

**Issue by ScottSmith95** [faceyspacey/extract-css-chunks-webpack-plugin#162]
`TypeError: this[MODULE_TYPE] is not a function` under version `4.x` when used in a node build process akin to https://github.com/nozzle/react-static/blob/master/packages/react-static-plugin-css-modules/src/node.api.js (despite updating the API as noted in the changelog)

**Comment by ScriptedAlchemy** [comment]
What if you install 4.0.0? Without the ^? Trying to debug if it’s my latest webpack stuff

**Comment by ScottSmith95** [comment]
I tested on 4.0.0 when the update was released and then 4.2.0. I did find I had to add web pack as a dependency at which point the site would build on dev, but fail on production.

**Comment by ScriptedAlchemy** [comment]
okay so i know about that and i patched it on v4.0.2 - can you let me know if this works for you. Im away from my machine but will investigate whats going on when i get home tonight

**Comment by ScriptedAlchemy** [comment]
Ahh well according to that plugin, it's using a very old API v3 of extract css chunks

**Comment by ScriptedAlchemy** [comment]
I have seen the module_type issue before though
Its related to a namespacing issue if im correct, which im pretty sure was fixed.

Ill re-check this

**Comment by ScottSmith95** [comment]
I appreciate it. Any help you have. You helped me earlier by creating the React Static plugin so I appreciate any insight.

**Comment by dptoot** [comment]
I am seeing this issue as well and would appreciate any assistance

**Comment by ScriptedAlchemy** [comment]
https://github.com/webpack-contrib/mini-css-extract-plugin/issues/73

**Comment by ScriptedAlchemy** [comment]
ur using it without the plugin, check mini-css reports on this issue

**Comment by aendrew** [comment]
Please re-open this, the latest version is very broken.

https://github.com/aendrew/extract-css-chunks-webpack-plugin-162

I use sass-loader in this repro because that was my original error case but it still yields the same error if you comment it out.

**Comment by ScriptedAlchemy** [comment]
Usually caused by either a missing plugin or loader.

**Comment by ScriptedAlchemy** [comment]
Html webpack plugin is ancient. If I’m correct, v3 doesn’t even work with webpack 4. Upgrade to the latest, there’s a v4 beta out

**Comment by aendrew** [comment]
@ScriptedAlchemy I've upgraded `html-webpack-plugin` to the `beta` version and I get the same error as before; please check the minimal repro I posted, have updated it.

**Comment by ScriptedAlchemy** [comment]
okay, ill check it out. Have you tried deleting all your node modules and yarn/package lock files? 
Usually, things get stuck. 

Beyond that, there's a tool called `npm-upgrade` which is very useful

**Comment by Slach** [comment]
could we re-open this issue? i get same error with latest version of webpack and babel

**Comment by ScriptedAlchemy** [comment]
I’ll take a look and consult with some webpack authors. Thanks for bringing this to my attention

**Comment by CermakM** [comment]
Any update on this one, please? Same issue.

**Comment by sayjeyhi** [comment]
I have this error too , with SSR , full error :
```bash
ERROR in ./app/resources/styles/sanitize.css
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
TypeError: this[MODULE_TYPE] is not a function
    at C:\Users\SayJeyHi\PhpstormProjects\snapp\new-website\node_modules\mini-css-extract-plugin\dist\loader.js:170:24
    at C:\Users\SayJeyHi\PhpstormProjects\snapp\new-website\node_modules\webpack\lib\Compiler.js:343:11
    at C:\Users\SayJeyHi\PhpstormProjects\snapp\new-website\node_modules\webpack\lib\Compiler.js:681:15
    at AsyncSeriesHook.eval [as callAsync] (eval at create (C:\Users\SayJeyHi\PhpstormProjects\snapp\new-website\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:24:1)
    at AsyncSeriesHook.lazyCompileHook (C:\Users\SayJeyHi\PhpstormProjects\snapp\new-website\node_modules\tapable\lib\Hook.js:154:20)
    at C:\Users\SayJeyHi\PhpstormProjects\snapp\new-website\node_modules\webpack\lib\Compiler.js:678:31
    at AsyncSeriesHook.eval [as callAsync] (eval at create (C:\Users\SayJeyHi\PhpstormProjects\snapp\new-website\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (C:\Users\SayJeyHi\PhpstormProjects\snapp\new-website\node_modules\tapable\lib\Hook.js:154:20)
    at C:\Users\SayJeyHi\PhpstormProjects\snapp\new-website\node_modules\webpack\lib\Compilation.js:1423:35
    at AsyncSeriesHook.eval [as callAsync] (eval at create (C:\Users\SayJeyHi\PhpstormProjects\snapp\new-website\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:6:1)
 @ ./app/components/global/styles.js 67:0-45
 @ ./app/components/global/Hoc/index.js
 @ ./app/appServer.js
 @ multi webpack-hot-middleware/client?reload=true ./app/appServer.js
```

**Comment by akashishu777** [comment]
Can anyone help me how to fix 
**TypeError: Class constructor HookCodeFactory cannot be invoked without 'new'**

This is happening in production

 "webpack": "~4.25.1"

```
[02:47:00][npm run portal-prod] E:\BuildAgent\work\83d9728970ba3129\node_modules\tapable\lib\SyncWaterfallHook.js:24
[02:47:00][npm run portal-prod] 		});
[02:47:00][npm run portal-prod]                                          ^
[02:47:00][npm run portal-prod] TypeError: Class constructor HookCodeFactory cannot be invoked without 'new'
[02:47:00][npm run portal-prod]     at new SyncWaterfallHookCodeFactory (E:\BuildAgent\work\83d9728970ba3129\node_modules\tapable\lib\SyncWaterfallHook.js:24:42)
[02:47:00][npm run portal-prod]     at Object.<anonymous> (E:\BuildAgent\work\83d9728970ba3129\node_modules\tapable\lib\SyncWaterfallHook.js:28:17)
[02:47:00][npm run portal-prod]     at Module._compile (E:\BuildAgent\work\83d9728970ba3129\node_modules\v8-compile-cache\v8-compile-cache.js:194:30)
[02:47:00][npm run portal-prod]     at Module.m._compile (E:\BuildAgent\work\83d9728970ba3129\node_modules\ts-node\src\index.ts:536:23)
[02:47:00][npm run portal-prod]     at Module._extensions..js (module.js:664:10)
[02:47:00][npm run portal-prod]     at Object.require.extensions.(anonymous function) [as .js] (E:\BuildAgent\work\83d9728970ba3129\node_modules\ts-node\src\index.ts:539:12)
[02:47:00][npm run portal-prod]     at Module.load (module.js:566:32)
[02:47:00][npm run portal-prod]     at tryModuleLoad (module.js:506:12)
[02:47:00][npm run portal-prod]     at Function.Module._load (module.js:498:3)
[02:47:00][npm run portal-prod]     at Module.require (module.js:597:17)
```



Webpack.config

```
{
	test: /\.(scss|sass|css|)$/,
			use: [
					MiniCssExtractPlugin.loader,
					"css-loader",
					"sass-loader"
				]
			}
	plugins: [
		new CleanWebpackPlugin(['dist']),
		new MiniCssExtractPlugin({
			filename: 'bundle.css'
		}),
		new webpack.DefinePlugin({
			'process.env.NODE_ENV': JSON.stringify('production')
		}),
```

**Comment by ngattusohw** [comment]
Was this ever resolved? I am still getting this issue as well

**Comment by bendog** [comment]
I'm also suffering from this issue.

**Comment by wagnerjsilva** [comment]
Also having the same issue.
