### ISSUE TITLE
Compatibility with AngularCompilerPlugin

### ISSUE THREAD

**Issue by ViieeS** [faceyspacey/extract-css-chunks-webpack-plugin#169]
Try to use ExtractCssChunksPlugin with AngularCompilerPlugin but get error:

```log
ERROR in Module build failed (from ../node_modules/extract-css-chunks-webpack-plugin/dist/loader.js):
TypeError: Cannot read property 'replace' of undefined
    at normalizeBackSlashDirection (/Projects/Web/frontend/node_modules/webpack/lib/RequestShortener.js:16:17)
    at new RequestShortener (/Projects/Web/frontend/node_modules/webpack/lib/RequestShortener.js:26:15)
    at new Compiler (/Projects/Web/frontend/node_modules/webpack/lib/Compiler.js:185:27)
    at Compiler.createChildCompiler (/Projects/Web/frontend/node_modules/webpack/lib/Compiler.js:508:25)
    at Compilation.createChildCompiler (/Projects/Web/frontend/node_modules/webpack/lib/Compilation.js:2498:24)
    at Object.pitch (/Projects/Web/frontend/node_modules/extract-css-chunks-webpack-plugin/dist/loader.js:90:43)
ℹ ｢wdm｣: Failed to compile.
```
Similar problem with mini-css-extract-plugin: https://github.com/webpack-contrib/mini-css-extract-plugin/issues/186

**Comment by ScriptedAlchemy** [comment]
Try it now

**Comment by ViieeS** [comment]
@ScriptedAlchemy same error on `ExtractCssChunksPlugin v4.4.0`

**Comment by nickbullock** [comment]
Got it too. Here is a minimum repro https://github.com/nickbullock/angular-mini-css-extract-plugin-example
npm run start - and you can see this error in console
