### ISSUE TITLE
Support onlyLocals parameters in css-loader

### ISSUE THREAD

**Issue by Tom910** [faceyspacey/extract-css-chunks-webpack-plugin#261]
if enable `onlyLocals` in [css-loader](https://github.com/webpack-contrib/css-loader#onlylocals) i get error. `onlyLocals` remove generation css content in SSR
```
TypeError: Cannot read property 'length' of undefined
    at CssModule.size (/Users/User/job/platform-cli/node_modules/extract-css-chunks-webpack-plugin/dist/index.js:58:25)
    at Chunk.integratedSize (/Users/User/job/platform-cli/node_modules/webpack/lib/Chunk.js:548:42)
    at orderedChunks.forEach (/Users/User/job/platform-cli/node_modules/webpack/lib/optimize/LimitChunkCountPlugin.js:96:33)
    at Array.forEach (<anonymous>)
    at compilation.hooks.optimizeChunksAdvanced.tap.chunks (/Users/User/job/platform-cli/node_modules/webpack/lib/optimize/LimitChunkCountPlugin.js:92:20)
    at SyncBailHook.eval [as call] (eval at create (/Users/User/job/platform-cli/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:12:16)
    at SyncBailHook.lazyCompileHook (/Users/User/job/platform-cli/node_modules/tapable/lib/Hook.js:154:20)
```

**Comment by ScriptedAlchemy** [comment]
What about modules. IsonlyLocals still valid?
