### ISSUE TITLE
Webpack 5 Error: window is not defined

### ISSUE THREAD

**Issue by meskill** [faceyspacey/extract-css-chunks-webpack-plugin#289]
Prerequisites:
- webpack@5.0.0-beta.23
- extract-css-chunks-webpack-plugin@4.7.5
- file-loader@6.0.0

Using webpack 5 when building css with svg inside:
```
.checkIcon {
    width: 24px;
    height: 24px;
    background: url(./icons/check.svg);
    -webkit-animation: bounce .225s;
            animation: bounce .225s;
}
```

loaders config: 
```
{
  test: /\.svg$/,
  use: [
    { loader: 'file-loader' },
    {
      loader: 'svgo-loader',
      options: { plugins: [ { cleanupIDs: false }, { collapseGroups: false } ] }
    }
  ]
}
{
  test: /\.css$/,
  use: [
    {
      loader: 'F:\\Tinkoff\\platform-cli\\node_modules\\extract-css-chunks-webpack-plugin\\dist\\loader.js',
      options: { esModule: false }
    },
    {
      loader: 'css-loader',
      options: {
        modules: {
          localIdentName: '[name]__[local]_[hash:base64:5]',
          getLocalIdent: [Function]
        },
        sourceMap: false,
        importLoaders: 1,
        esModule: false
      }
    },
    {
      loader: 'postcss-loader',
      options: { sourceMap: false, plugins: [Function: plugins] }
    }
  ]
}

```

will cause build to fail with error:
```
Error: Module build failed (from ../../node_modules/extract-css-chunks-webpack-plugin/dist/loader.js):
ReferenceError: window is not defined
    at F:\Tinkoff\platform-cli\node_modules\cache-loader\dist\cjs.js??ruleSet[1].rules[13].use[1]!F:\Tinkoff\platform-cli\node_modules\css-loader\dist\cjs.js??ruleSet[1].rules[13].use[2]!F:\Tinkoff\platform-cli\node_modules\
postcss-loader\src\index.js??ruleSet[1].rules[13].use[3]!F:\Tinkoff\tramvai\node_modules\@platform-ui\inputAutocomplete\node_modules\@platform-ui\input\Input.css:275:36
    at F:\Tinkoff\platform-cli\node_modules\cache-loader\dist\cjs.js??ruleSet[1].rules[13].use[1]!F:\Tinkoff\platform-cli\node_modules\css-loader\dist\cjs.js??ruleSet[1].rules[13].use[2]!F:\Tinkoff\platform-cli\node_modules\
postcss-loader\src\index.js??ruleSet[1].rules[13].use[3]!F:\Tinkoff\tramvai\node_modules\@platform-ui\inputAutocomplete\node_modules\@platform-ui\input\Input.css:276:13
    at Object.<anonymous> (F:\Tinkoff\platform-cli\node_modules\cache-loader\dist\cjs.js??ruleSet[1].rules[13].use[1]!F:\Tinkoff\platform-cli\node_modules\css-loader\dist\cjs.js??ruleSet[1].rules[13].use[2]!F:\Tinkoff\platfo
rm-cli\node_modules\postcss-loader\src\index.js??ruleSet[1].rules[13].use[3]!F:\Tinkoff\tramvai\node_modules\@platform-ui\inputAutocomplete\node_modules\@platform-ui\input\Input.css:283:12)
    at Module._compile (F:\Tinkoff\platform-cli\node_modules\v8-compile-cache\v8-compile-cache.js:194:30)
    at evalModuleCode (F:\Tinkoff\platform-cli\node_modules\extract-css-chunks-webpack-plugin\dist\loader.js:61:10)
    at F:\Tinkoff\platform-cli\node_modules\extract-css-chunks-webpack-plugin\dist\loader.js:166:21
    at F:\Tinkoff\platform-cli\node_modules\webpack\lib\Compiler.js:486:11
    at F:\Tinkoff\platform-cli\node_modules\webpack\lib\Compiler.js:981:17
    at Hook.eval [as callAsync] (eval at create (F:\Tinkoff\platform-cli\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:15:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (F:\Tinkoff\platform-cli\node_modules\webpack\node_modules\tapable\lib\Hook.js:18:14)
    at F:\Tinkoff\platform-cli\node_modules\webpack\lib\Compiler.js:977:33
    at Hook.eval [as callAsync] (eval at create (F:\Tinkoff\platform-cli\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (F:\Tinkoff\platform-cli\node_modules\webpack\node_modules\tapable\lib\Hook.js:18:14)
    at F:\Tinkoff\platform-cli\node_modules\webpack\lib\Compilation.js:1999:37
    at eval (eval at create (F:\Tinkoff\platform-cli\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:11:1)
    at F:\Tinkoff\platform-cli\node_modules\csso-webpack-plugin\lib\index.js:158:21
    at F:\Tinkoff\platform-cli\packages\cli\lib\commands\build\utils\webpackBuild.js:20:21
    at F:\Tinkoff\platform-cli\node_modules\webpack\lib\webpack.js:123:6
    at F:\Tinkoff\platform-cli\node_modules\webpack\lib\HookWebpackError.js:69:3
    at Hook.eval [as callAsync] (eval at create (F:\Tinkoff\platform-cli\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (F:\Tinkoff\platform-cli\node_modules\webpack\node_modules\tapable\lib\Hook.js:18:14)
    at Cache.shutdown (F:\Tinkoff\platform-cli\node_modules\webpack\lib\Cache.js:150:23)
    at Compiler.close (F:\Tinkoff\platform-cli\node_modules\webpack\lib\Compiler.js:996:14)
    at F:\Tinkoff\platform-cli\node_modules\webpack\lib\webpack.js:122:14
    at finalCallback (F:\Tinkoff\platform-cli\node_modules\webpack\lib\Compiler.js:367:32)
    at F:\Tinkoff\platform-cli\node_modules\webpack\lib\Compiler.js:384:13
    at Hook.eval [as callAsync] (eval at create (F:\Tinkoff\platform-cli\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (F:\Tinkoff\platform-cli\node_modules\webpack\node_modules\tapable\lib\Hook.js:18:14)
    at onCompiled (F:\Tinkoff\platform-cli\node_modules\webpack\lib\Compiler.js:382:21)
    at F:\Tinkoff\platform-cli\node_modules\webpack\lib\Compiler.js:981:17
    at Hook.eval [as callAsync] (eval at create (F:\Tinkoff\platform-cli\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (F:\Tinkoff\platform-cli\node_modules\webpack\node_modules\tapable\lib\Hook.js:18:14)
```

with webpack 4 it works without problems

**Comment by meskill** [comment]
It was problem coming from other plugin, as problem was reproducible for mini-css-extract-plugin
