### ISSUE TITLE
CSS cannot be loaded. At all.

### ISSUE THREAD

**Issue by re6exp** [faceyspacey/extract-css-chunks-webpack-plugin#81]
Trying to use UC-family updated to use WP4.
Any attempt to load css failed.

- "extract-css-chunks-webpack-plugin": "^3.0.6",
- "webpack": "^4.12.0",
- "css-loader": "^0.28.11",

There is a simple css file with css classes defined, I load them like `import {myClassName} from 'file.css'`:
```
    {
        test: /\.css$/,
        use: [
            ExtractCssChunks.loader,
           {
                loader: 'css-loader',
                options: {
                    modules: true,
                    camelCase: true
               }
        }]
    },
```

And then I get this:
<details><summary><i>trace (Click to show)</i></summary>
<p>

```
/home/anton/Documents/workspace-sts/nodejs-spring-cloud-app-boilerplate/node_modules/babel-core/lib/transformation/file/index.js:558
      throw err;
      ^

SyntaxError: /home/anton/Documents/workspace-sts/nodejs-spring-cloud-app-boilerplate/src/client/App.css: Unexpected token (1:0)
> 1 | .app {
    | ^
  2 |   text-align: center; }
  3 | 
  4 | .app-logo {
    at Parser.pp$5.raise (/home/anton/Documents/workspace-sts/nodejs-spring-cloud-app-boilerplate/node_modules/babylon/lib/index.js:4454:13)
    at Parser.pp.unexpected (/home/anton/Documents/workspace-sts/nodejs-spring-cloud-app-boilerplate/node_modules/babylon/lib/index.js:1761:8)
    at Parser.pp$3.parseExprAtom (/home/anton/Documents/workspace-sts/nodejs-spring-cloud-app-boilerplate/node_modules/babylon/lib/index.js:3750:12)
    at Parser.parseExprAtom (/home/anton/Documents/workspace-sts/nodejs-spring-cloud-app-boilerplate/node_modules/babylon/lib/index.js:7238:22)
    at Parser.pp$3.parseExprSubscripts (/home/anton/Documents/workspace-sts/nodejs-spring-cloud-app-boilerplate/node_modules/babylon/lib/index.js:3494:19)
    at Parser.pp$3.parseMaybeUnary (/home/anton/Documents/workspace-sts/nodejs-spring-cloud-app-boilerplate/node_modules/babylon/lib/index.js:3474:19)
    at Parser.pp$3.parseExprOps (/home/anton/Documents/workspace-sts/nodejs-spring-cloud-app-boilerplate/node_modules/babylon/lib/index.js:3404:19)
    at Parser.pp$3.parseMaybeConditional (/home/anton/Documents/workspace-sts/nodejs-spring-cloud-app-boilerplate/node_modules/babylon/lib/index.js:3381:19)
    at Parser.pp$3.parseMaybeAssign (/home/anton/Documents/workspace-sts/nodejs-spring-cloud-app-boilerplate/node_modules/babylon/lib/index.js:3344:19)
    at Parser.parseMaybeAssign (/home/anton/Documents/workspace-sts/nodejs-spring-cloud-app-boilerplate/node_modules/babylon/lib/index.js:6474:20)
error Command failed with exit code 1.
```
</p>
</details>

<br/>
Here is babelrc content (just in case):
<br/>
<br/>
<details><summary><i>babel cfg (Click to show)</i></summary>
<p>
```
{
    'presets': [
        [ 'env', {
            targets: {
                browsers: ['last 2 chrome versions']
            },
            modules: 'commonjs'
        }],
        'react',
    ],
    'plugins': [
        [
            'module-resolver',
            {
                'root': ['./src'],
                'alias': {
                    'client': './src/client',
                    ...
                    'server': './src/server',
                }
            }
        ],
        'react-hot-loader/babel',
        'universal-import',
        
        ['transform-class-properties', { spec: true } ],
        'transform-object-rest-spread'
    ]
}
```
</p>
</details>

**Comment by re6exp** [comment]
And here is some piece of webpack config:
<br/>
<details><summary><i>webpack cfg (Click to show)</i></summary>
<p>
```
 new ExtractCssChunks(
            {
              // Options similar to the same options in webpackOptions.output
              // both options are optional
              filename: '[name].css',
              chunkFilename: '[id].css',
              hot: true // optional as the plugin cannot automatically detect if you are using HOT, not for production use
            }
        ),
    ],

    optimization: {
        namedChunks: true,
        splitChunks: {
            chunks: 'async',
            minSize: 30000,
            minChunks: 1,
            maxAsyncRequests: 5,
            maxInitialRequests: 3,
            automaticNameDelimiter: '~',
            name: true,
            cacheGroups: {
                vendors: {
                    test: /[\\/]node_modules[\\/]/,
                    priority: -10
                },
                default: {
                    minChunks: 2,
                    priority: -20,
                    reuseExistingChunk: true
                }
            }
        }
    },
```
</p>
</details>

**Comment by re6exp** [comment]
I found the [solution](https://github.com/webpack/webpack/issues/1754). Very interesting.

**Comment by ScriptedAlchemy** [comment]
Ahhhh! Good find - thanks for the exploratory work done

**Comment by re6exp** [comment]
If you use custom bootstrap to load Webpack like me, not by <webpack [args]>, Babel stumbles on non-js files. In this case there is ignore-styles component that does the job. Or we can ignore them by hands in babelrc.
