### ISSUE TITLE
"SyntaxError: Invalid Unicode escape sequence"

### ISSUE THREAD

**Issue by fkranenburg** [faceyspacey/extract-css-chunks-webpack-plugin#88]
I get a strange build error. It looks like it is related if a subfolder starts with the letter 'u'.

This is the error I receive (check out the ^^^^) :
![image](https://user-images.githubusercontent.com/5680394/42945981-1accb77c-8b6a-11e8-9246-2e819f100b9a.png)

This is the stacktrace:

`SyntaxError: Invalid Unicode escape sequence
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:607:28)
    at exec (C:\Github\AuditCase\nl.c2c.ac.resources\web\node_modules\extract-css-chunks-webpack-plugin\dist\loader.js:56:10)
    at childCompiler.runAsChild (C:\Github\AuditCase\nl.c2c.ac.resources\web\node_modules\extract-css-chunks-webpack-plugin\dist\loader.js:133:14)
    at compile (C:\Github\AuditCase\nl.c2c.ac.resources\web\node_modules\webpack\lib\Compiler.js:243:11)
    at hooks.afterCompile.callAsync.err (C:\Github\AuditCase\nl.c2c.ac.resources\web\node_modules\webpack\lib\Compiler.js:500:14)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (C:\Github\AuditCase\nl.c2c.ac.resources\web\node_modules\tapable\lib\HookCodeFactory.js:24:12), <anonymous>:24:1)
    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (C:\Github\AuditCase\nl.c2c.ac.resources\web\node_modules\tapable\lib\Hook.js:35:21)
    at compilation.seal.err (C:\Github\AuditCase\nl.c2c.ac.resources\web\node_modules\webpack\lib\Compiler.js:497:30)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (C:\Github\AuditCase\nl.c2c.ac.resources\web\node_modules\tapable\lib\HookCodeFactory.js:24:12), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (C:\Github\AuditCase\nl.c2c.ac.resources\web\node_modules\tapable\lib\Hook.js:35:21)
    at hooks.optimizeAssets.callAsync.err (C:\Github\AuditCase\nl.c2c.ac.resources\web\node_modules\webpack\lib\Compilation.js:986:35)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (C:\Github\AuditCase\nl.c2c.ac.resources\web\node_modules\tapable\lib\HookCodeFactory.js:24:12), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (C:\Github\AuditCase\nl.c2c.ac.resources\web\node_modules\tapable\lib\Hook.js:35:21)
    at hooks.optimizeChunkAssets.callAsync.err (C:\Github\AuditCase\nl.c2c.ac.resources\web\node_modules\webpack\lib\Compilation.js:977:32)`

I got this in version 3.0.6 and it still exists in version 3.0.9

**Comment by ScriptedAlchemy** [comment]
I myself am using utils directories all over the place, but never has this been an issue. Could you create a sample repo with this? Might it be an invisible character or something? I've seen it before when pasting a file or directory name. Even though it looked normal, then characters were not the correct Unicode format

**Comment by fkranenburg** [comment]
It was fixed in the other plugin: https://github.com/OpenNTF/dojo-webpack-plugin/issues/174
