### ISSUE TITLE
vue ssr build : ReferenceError: document is not defined

### ISSUE THREAD

**Issue by zdliuccit** [faceyspacey/extract-css-chunks-webpack-plugin#94]
Module build failed (from ./node_modules/extract-css-chunks-webpack-plugin/dist/loader.js):
ReferenceError: document is not defined
    at addStyle (/Users/liuzhengdong/Documents/works/vue/render/node_modules/vue-style-loader/index.js!/Users/liuzhengdong/Documents/works/vue/render/node_modules/css-loader/index.js!/Users/liuzhengdong/Documents/works/vue/render/node_modules/vue-loader/lib/loaders/stylePostLoader.js!/Users/liuzhengdong/Documents/works/vue/render/node_modules/postcss-loader/lib/index.js!/Users/liuzhengdong/Documents/works/vue/render/node_modules/stylus-loader/index.js!/Users/liuzhengdong/Documents/works/vue/render/node_modules/vue-loader/lib/index.js??vue-loader-options!/Users/liuzhengdong/Documents/works/vue/render/client/home.vue?vue&type=style&index=0&id=49d0e07f&lang=stylus&scoped=true&:355:22)
    at addStylesToDom (/Users/liuzhengdong/Documents/works/vue/render/node_modules/vue-style-loader/index.js!/Users/liuzhengdong/Documents/works/vue/render/node_modules/css-loader/index.js!/Users/liuzhengdong/Documents/works/vue/render/node_modules/vue-loader/lib/loaders/stylePostLoader.js!/Users/liuzhengdong/Documents/works/vue/render/node_modules/postcss-loader/lib/index.js!/Users/liuzhengdong/Documents/works/vue/render/node_modules/stylus-loader/index.js!/Users/liuzhengdong/Documents/works/vue/render/node_modules/vue-loader/lib/index.js??vue-loader-options!/Users/liuzhengdong/Documents/works/vue/render/client/home.vue?vue&type=style&index=0&id=49d0e07f&lang=stylus&scoped=true&:339:20)
    at addStylesClient (/Users/liuzhengdong/Documents/works/vue/render/node_modules/vue-style-loader/index.js!/Users/liuzhengdong/Documents/works/vue/render/node_modules/css-loader/index.js!/Users/liuzhengdong/Documents/works/vue/render/node_modules/vue-loader/lib/loaders/stylePostLoader.js!/Users/liuzhengdong/Documents/works/vue/render/node_modules/postcss-loader/lib/index.js!/Users/liuzhengdong/Documents/works/vue/render/node_modules/stylus-loader/index.js!/Users/liuzhengdong/Documents/works/vue/render/node_modules/vue-loader/lib/index.js??vue-loader-options!/Users/liuzhengdong/Documents/works/vue/render/client/home.vue?vue&type=style&index=0&id=49d0e07f&lang=stylus&scoped=true&:293:3)
    at Object.<anonymous> (/Users/liuzhengdong/Documents/works/vue/render/node_modules/vue-style-loader/index.js!/Users/liuzhengdong/Documents/works/vue/render/node_modules/css-loader/index.js!/Users/liuzhengdong/Documents/works/vue/render/node_modules/vue-loader/lib/loaders/stylePostLoader.js!/Users/liuzhengdong/Documents/works/vue/render/node_modules/postcss-loader/lib/index.js!/Users/liuzhengdong/Documents/works/vue/render/node_modules/stylus-loader/index.js!/Users/liuzhengdong/Documents/works/vue/render/node_modules/vue-loader/lib/index.js??vue-loader-options!/Users/liuzhengdong/Documents/works/vue/render/client/home.vue?vue&type=style&index=0&id=49d0e07f&lang=stylus&scoped=true&:100:14)
    at __webpack_require__ (/Users/liuzhengdong/Documents/works/vue/render/node_modules/vue-style-loader/index.js!/Users/liuzhengdong/Documents/works/vue/render/node_modules/css-loader/index.js!/Users/liuzhengdong/Documents/works/vue/render/node_modules/vue-loader/lib/loaders/stylePostLoader.js!/Users/liuzhengdong/Documents/works/vue/render/node_modules/postcss-loader/lib/index.js!/Users/liuzhengdong/Documents/works/vue/render/node_modules/stylus-loader/index.js!/Users/liuzhengdong/Documents/works/vue/render/node_modules/vue-loader/lib/index.js??vue-loader-options!/Users/liuzhengdong/Documents/works/vue/render/client/home.vue?vue&type=style&index=0&id=49d0e07f&lang=stylus&scoped=true&:21:30)
    at /Users/liuzhengdong/Documents/works/vue/render/node_modules/vue-style-loader/index.js!/Users/liuzhengdong/Documents/works/vue/render/node_modules/css-loader/index.js!/Users/liuzhengdong/Documents/works/vue/render/node_modules/vue-loader/lib/loaders/stylePostLoader.js!/Users/liuzhengdong/Documents/works/vue/render/node_modules/postcss-loader/lib/index.js!/Users/liuzhengdong/Documents/works/vue/render/node_modules/stylus-loader/index.js!/Users/liuzhengdong/Documents/works/vue/render/node_modules/vue-loader/lib/index.js??vue-loader-options!/Users/liuzhengdong/Documents/works/vue/render/client/home.vue?vue&type=style&index=0&id=49d0e07f&lang=stylus&scoped=true&:85:18
    at Object.<anonymous> (/Users/liuzhengdong/Documents/works/vue/render/node_modules/vue-style-loader/index.js!/Users/liuzhengdong/Documents/works/vue/render/node_modules/css-loader/index.js!/Users/liuzhengdong/Documents/works/vue/render/node_modules/vue-loader/lib/loaders/stylePostLoader.js!/Users/liuzhengdong/Documents/works/vue/render/node_modules/postcss-loader/lib/index.js!/Users/liuzhengdong/Documents/works/vue/render/node_modules/stylus-loader/index.js!/Users/liuzhengdong/Documents/works/vue/render/node_modules/vue-loader/lib/index.js??vue-loader-options!/Users/liuzhengdong/Documents/works/vue/render/client/home.vue?vue&type=style&index=0&id=49d0e07f&lang=stylus&scoped=true&:88:10)
    at Module._compile (/Users/liuzhengdong/Documents/works/vue/render/node_modules/v8-compile-cache/v8-compile-cache.js:178:30)
    at exec (/Users/liuzhengdong/Documents/works/vue/render/node_modules/extract-css-chunks-webpack-plugin/dist/loader.js:56:10)
    at childCompiler.runAsChild (/Users/liuzhengdong/Documents/works/vue/render/node_modules/extract-css-chunks-webpack-plugin/dist/loader.js:131:14)
    at compile (/Users/liuzhengdong/Documents/works/vue/render/node_modules/webpack/lib/Compiler.js:296:11)
    at hooks.afterCompile.callAsync.err (/Users/liuzhengdong/Documents/works/vue/render/node_modules/webpack/lib/Compiler.js:553:14)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/liuzhengdong/Documents/works/vue/render/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:15:1)
    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (/Users/liuzhengdong/Documents/works/vue/render/node_modules/tapable/lib/Hook.js:35:21)
    at compilation.seal.err (/Users/liuzhengdong/Documents/works/vue/render/node_modules/webpack/lib/Compiler.js:550:30)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/liuzhengdong/Documents/works/vue/render/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (/Users/liuzhengdong/Documents/works/vue/render/node_modules/tapable/lib/Hook.js:35:21)
    at hooks.optimizeAssets.callAsync.err (/Users/liuzhengdong/Documents/works/vue/render/node_modules/webpack/lib/Compilation.js:1284:35)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/liuzhengdong/Documents/works/vue/render/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (/Users/liuzhengdong/Documents/works/vue/render/node_modules/tapable/lib/Hook.js:35:21)
    at hooks.optimizeChunkAssets.callAsync.err (/Users/liuzhengdong/Documents/works/vue/render/node_modules/webpack/lib/Compilation.js:1275:32)
    at _err1 (eval at create (/Users/liuzhengdong/Documents/works/vue/render/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:15:1)
    at /Users/liuzhengdong/Documents/works/vue/render/node_modules/uglifyjs-webpack-plugin/dist/index.js:282:11
    at _class.runTasks (/Users/liuzhengdong/Documents/works/vue/render/node_modules/uglifyjs-webpack-plugin/dist/uglify/index.js:63:9)
    at UglifyJsPlugin.optimizeFn (/Users/liuzhengdong/Documents/works/vue/render/node_modules/uglifyjs-webpack-plugin/dist/index.js:195:16)
    at _fn0.then._result0 (eval at create (/Users/liuzhengdong/Documents/works/vue/render/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:11:1)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

 @ ./client/home.vue?vue&type=style&index=0&id=49d0e07f&lang=stylus&scoped=true& 1:0-435 1:451-454 1:456-888 1:456-888
 @ ./client/home.vue
 @ ./client/router.js
 @ ./client/index.js
 @ ./client/entry-client.js

**Comment by dmitrif** [comment]
Whats the solution?
