### ISSUE TITLE
Error: Cannot find module 'extract-css-chunks-webpack-plugin'

### ISSUE THREAD

**Issue by parth55** [faceyspacey/extract-css-chunks-webpack-plugin#95]
Hi,
I have installed "extract-css-chunks-webpack-plugin" via 
npm install extract-css-chunks-webpack-plugin --only=dev
and called it in webpack.config.js file as below
var ExtractCssChunks = require("extract-css-chunks-webpack-plugin");

but its giving me below error

module.js:549
    throw err;
    ^

Error: Cannot find module 'extract-css-chunks-webpack-plugin'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (d:\WebDevelopment\Webpack-Setup\webpack.config.js:3:24)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)

can you please help me?

**Comment by ScriptedAlchemy** [comment]
Likely a yarn lock or package lock file. 

If not. Are you trying to NPM link the package elsewhere?

**Comment by parth55** [comment]
I have uninstalled and installed it again and the issue has been sorted.
Thanks.

**Comment by ScriptedAlchemy** [comment]
@parth55 yeah man, especially with `yarn` its buggy when it comes to stuff like this
