### ISSUE TITLE
Runtime error with v^3.0.11

### ISSUE THREAD

**Issue by dmitrif** [faceyspacey/extract-css-chunks-webpack-plugin#96]
Following error with latest:

```
fes_1  |     Error: Module build failed (from ./node_modules/extract-css-chunks-webpack-plugin/dist/loader.js):
fes_1  |     TypeError: this[NS] is not a function
fes_1  |         at childCompiler.runAsChild (/var/frontend/node_modules/extract-css-chunks-webpack-plugin/dist/loader.js:146:15)
fes_1  |         at compile (/var/frontend/node_modules/webpack/lib/Compiler.js:296:11)
fes_1  |         at hooks.afterCompile.callAsync.err (/var/frontend/node_modules/webpack/lib/Compiler.js:553:14)
fes_1  |         at AsyncSeriesHook.eval [as callAsync] (eval at create (/var/frontend/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:24:1)
fes_1  |         at AsyncSeriesHook.lazyCompileHook [as _callAsync] (/var/frontend/node_modules/tapable/lib/Hook.js:35:21)
fes_1  |         at compilation.seal.err (/var/frontend/node_modules/webpack/lib/Compiler.js:550:30)
fes_1  |         at AsyncSeriesHook.eval [as callAsync] (eval at create (/var/frontend/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:6:1)
fes_1  |         at AsyncSeriesHook.lazyCompileHook [as _callAsync] (/var/frontend/node_modules/tapable/lib/Hook.js:35:21)
fes_1  |         at hooks.optimizeAssets.callAsync.err (/var/frontend/node_modules/webpack/lib/Compilation.js:1284:35)
fes_1  |         at AsyncSeriesHook.eval [as callAsync] (eval at create (/var/frontend/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:6:1)
fes_1  |         at AsyncSeriesHook.lazyCompileHook [as _callAsync] (/var/frontend/node_modules/tapable/lib/Hook.js:35:21)
fes_1  |         at hooks.optimizeChunkAssets.callAsync.err (/var/frontend/node_modules/webpack/lib/Compilation.js:1275:32)
fes_1  |         at AsyncSeriesHook.eval [as callAsync] (eval at create (/var/frontend/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:6:1)
fes_1  |         at AsyncSeriesHook.lazyCompileHook [as _callAsync] (/var/frontend/node_modules/tapable/lib/Hook.js:35:21)
fes_1  |         at hooks.additionalAssets.callAsync.err (/var/frontend/node_modules/webpack/lib/Compilation.js:1270:36)
fes_1  |         at AsyncSeriesHook.eval [as callAsync] (eval at create (/var/frontend/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:6:1)
fes_1  |         at AsyncSeriesHook.lazyCompileHook [as _callAsync] (/var/frontend/node_modules/tapable/lib/Hook.js:35:21)
fes_1  |         at hooks.optimizeTree.callAsync.err (/var/frontend/node_modules/webpack/lib/Compilation.js:1266:32)
fes_1  |         at AsyncSeriesHook.eval [as callAsync] (eval at create (/var/frontend/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:6:1)
fes_1  |         at AsyncSeriesHook.lazyCompileHook [as _callAsync] (/var/frontend/node_modules/tapable/lib/Hook.js:35:21)
fes_1  |         at Compilation.seal (/var/frontend/node_modules/webpack/lib/Compilation.js:1203:27)
fes_1  |         at hooks.make.callAsync.err (/var/frontend/node_modules/webpack/lib/Compiler.js:547:17)
fes_1  |         at _err0 (eval at create (/var/frontend/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:11:1)
fes_1  |         at _addModuleChain (/var/frontend/node_modules/webpack/lib/Compilation.js:1054:12)
fes_1  |         at processModuleDependencies.err (/var/frontend/node_modules/webpack/lib/Compilation.js:980:9)
fes_1  |         at _combinedTickCallback (internal/process/next_tick.js:131:7)
fes_1  |         at process._tickCallback (internal/process/next_tick.js:180:9)
fes_1  |         at eval (webpack:///./app/components/Banners/BannerStub.jss?:1:7)
fes_1  |         at Object../app/components/Banners/BannerStub.jss (/var/frontend/build/main.js:1856:1)
fes_1  |         at __webpack_require__ (/var/frontend/build/main.js:689:30)
fes_1  |         at fn (/var/frontend/build/main.js:60:20)
fes_1  |         at Object.eval (webpack:///./app/components/Banners/BannerStub.jsx?:19:19)
fes_1  |         at eval (webpack:///./app/components/Banners/BannerStub.jsx?:90:30)
fes_1  |         at Object../app/components/Banners/BannerStub.jsx (/var/frontend/build/main.js:1868:1)
fes_1  |         at __webpack_require__ (/var/frontend/build/main.js:689:30)
fes_1  |         at fn (/var/frontend/build/main.js:60:20)
fes_1  |         at Object.eval (webpack:///./app/components/Banners/Banner.jsx?:38:19)
fes_1  |         at eval (webpack:///./app/components/Banners/Banner.jsx?:267:30)
fes_1  |         at Object../app/components/Banners/Banner.jsx (/var/frontend/build/main.js:1845:1)
fes_1  |         at __webpack_require__ (/var/frontend/build/main.js:689:30)
fes_1  |         at fn (/var/frontend/build/main.js:60:20)
fes_1  |         at Object.eval (webpack:///./app/components/ViewItem/ViewItemPage.jsx?:78:15)
fes_1  |         at eval (webpack:///./app/components/ViewItem/ViewItemPage.jsx?:1075:30)
fes_1  |         at Object../app/components/ViewItem/ViewItemPage.jsx (/var/frontend/build/main.js:7893:1)
fes_1  |         at __webpack_require__ (/var/frontend/build/main.js:689:30)
fes_1  |         at fn (/var/frontend/build/main.js:60:20)
fes_1  |         at fn.t (/var/frontend/build/main.js:104:35)
fes_1  |         at <anonymous>
fes_1  |         at process._tickDomainCallback (internal/process/next_tick.js:228:7)```

**Comment by ScriptedAlchemy** [comment]
using it inside something like CRA

that compiler is multi-threaded (async) this component uses sync hooks in webpack 4. All hooks need to be updated to asyncTap functions

**Comment by dmitrif** [comment]
@ScriptedAlchemy We are using a homebrew webpack config here, but I don't think it's multi-threaded per-say. The previous loader in the chain is async and is using child compilers though, not sure if that's what triggers the issue in this case.

**Comment by dmitrif** [comment]
I think the issue is me, I forgot to add the plugin for the ssr build. Closing for now!

**Comment by ScriptedAlchemy** [comment]
Child compilers might have issue, i was removed from facebooks CRA repo because this thing can to child compilers in the Tappable API, least how i do it

**Comment by digitalkaoz** [comment]
@dmitrif @ScriptedAlchemy  im including the plugin everywhere i think, but still got the same error:

```
ERROR in /Users/caziel/workspace/own/eudw/src/scss/main.scss
Module build failed (from /Users/caziel/workspace/own/eudw/node_modules/extract-css-chunks-webpack-plugin/dist/loader.js):
TypeError: this[NS] is not a function
    at childCompiler.runAsChild (/Users/caziel/workspace/own/eudw/node_modules/extract-css-chunks-webpack-plugin/dist/loader.js:146:15)
    at compile (/Users/caziel/workspace/oss/react-static/node_modules/webpack/lib/Compiler.js:296:11)
    at hooks.afterCompile.callAsync.err (/Users/caziel/workspace/oss/react-static/node_modules/webpack/lib/Compiler.js:553:14)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/caziel/workspace/oss/react-static/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:15:1)
    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (/Users/caziel/workspace/oss/react-static/node_modules/tapable/lib/Hook.js:35:21)
    at compilation.seal.err (/Users/caziel/workspace/oss/react-static/node_modules/webpack/lib/Compiler.js:550:30)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/caziel/workspace/oss/react-static/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (/Users/caziel/workspace/oss/react-static/node_modules/tapable/lib/Hook.js:35:21)
    at hooks.optimizeAssets.callAsync.err (/Users/caziel/workspace/oss/react-static/node_modules/webpack/lib/Compilation.js:1284:35)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/caziel/workspace/oss/react-static/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (/Users/caziel/workspace/oss/react-static/node_modules/tapable/lib/Hook.js:35:21)
    at hooks.optimizeChunkAssets.callAsync.err (/Users/caziel/workspace/oss/react-static/node_modules/webpack/lib/Compilation.js:1275:32)
    at _fn1.then._result1 (eval at create (/Users/caziel/workspace/oss/react-static/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:15:1)
    at process._tickCallback (internal/process/next_tick.js:68:7)
 @ /Users/caziel/workspace/own/eudw/src/App.jsx 22:0-27
 @ /Users/caziel/workspace/own/eudw/src/index.js
Child extract-css-chunks-webpack-plugin css-loader/index.js??ref--4-oneOf-0-1!../../../own/eudw/node_modules/sass-loader/lib/loader.js??ref--4-oneOf-0-2!../../../own/eudw/src/scss/main.scss:
    [0] ./css-loader??ref--4-oneOf-0-1!/Users/caziel/workspace/own/eudw/node_modules/sass-loader/lib/loader.js??ref--4-oneOf-0-2!/Users/caziel/workspace/own/eudw/src/scss/main.scss 76 KiB {0} [built]
    [1] ./css-loader/lib/css-base.js 2.21 KiB {0} [built]

                => There were ERRORS during the prod build stage! :(
                => Fix them and try again!
```

any hints? in another project it works (boilerplate react-static with scss), in my case not and i dont see the difference what causes this error

**Comment by ScriptedAlchemy** [comment]
Looks like you are trying to create child threads or run webpack compilers multithreaded, or something. Same issue react CRA has. The css plugin doesn't work with async taps. child compilers do not have the same `this` context, meaning i cant execute the loader

**Comment by digitalkaoz** [comment]
And is there a solution? Multithreaded compiling sounds reasonable to me
(speedier builds)

Zack Jackson <notifications@github.com> schrieb am Sa., 18. Aug. 2018,
01:51:

**Comment by ScriptedAlchemy** [comment]
Original code is based off webpack themselves. If you reallllly need it then you’ll have to use style loader in dev. 

It’s a complete rewrite. I’ll have to get back in touch with webpack and see what’s doable. But don’t hold hopes man.
